version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es-container
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  email-client:
    build: .
    container_name: api-container
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch
    environment:
      - CLOUD_ID=${CLOUD_ID}
      - CLOUD_USERNAME=${CLOUD_USERNAME}
      - CLOUD_PASSWORD=${CLOUD_PASSWORD}

volumes:
  esdata:
    driver: local
